name:                haskell-web-warp
version:             0.1.0.0
github:              "Harmos274/haskell-warp-groundhog-api"
license:             BSD3
author:              "Lilian VERLHAC"
maintainer:          "lilian.verlhac@outlook.com"
copyright:           "2022 Lilian VERLHAC"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Harmos274/haskell-warp-groundhog-api#readme>

dependencies:
- base >= 4.7 && < 5
- warp
- wai
- utf8-string
- http-types
- blaze-builder
- text
- binary
- groundhog
- groundhog-postgresql
- groundhog-th
- aeson
- bytestring
- convertible

library:
  source-dirs: src
  ghc-options: -Wall

executables:
  haskell-web-warp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-web-warp

tests:
  haskell-web-warp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-web-warp
